### ISSUE TITLE
@CombinedParameters [Issue 37 @ googlecode]

### ISSUE THREAD

**Issue by plipinski** [Pragmatists/JUnitParams#1]
This is a feature-request.

I would like to propose a @CombinedParameters, the reason is that I dont want all my parameters to be in just one provider.

A quick example:

public @interface CombinedParameters {
    Parameters[] value();
}

---

@Test
@CombinedParameters(
    @Parameters(source = ProviderA.class),
    @Parameters(source = ProviderB.class)
)
public void test(String fromA, String fromB) {
    ...
}

---

public class ProviderA {
    public static Object[] provideStrings() {
        return $(
                    "A1",
                    "A2"
               );
    }
}

---

public class ProviderB {
    public static Object[] provideAString() {
        return $(
                    "B1"
               );
    }

    public static Object[] provideAnotherString() {
        return $(
                    "B2"
               );
    }
}

---

In this example, my test should be executed four times with the combines parameters like this:

test("A1", "B1")
test("A1", "B2")
test("A2", "B1")
test("A2", "B2")

----------------------------------------------
#1 brian@noerremark.dk
I thought about this again, at CombinedParameters should possibly extend Parameters, which would allow nesting CombinedParameters.

----------------------------------------------
#3 jim.newsham
I just discovered junitparams yesterday, and I think this project is great.  I had the same idea as this feature request, and I also feel that this feature should also be made available not only as "providers" but using the other mechanisms that junitparams supports such as providing method names.  For example:

  @Test
  @Parameters(method = "versions, flushTypes")
  public void rangeValidity(Version version, FlushType) throws Exception {
    ...
  }

I know that the current junitparams implementation would use versions() and flushTypes() to generate a single list of parameters, but I would like to use something like the above to produce a cross-product of the provided parameters as described earlier in this issue.

I realize this feature will not be implemented overnight, and since I need something of this sort immediately, I whipped up an interim hack which I would like to share here.  The following method produces a cross-product of parameters:

  private static Object[] product(Object[]... paramLists) {
    if (paramLists.length == 0) {
      return new Object[0];
    }
    
    int count = 1;
    for (int i = 0; i < paramLists.length; i++) {
      int listLength = paramLists[i].length;
      if (listLength == 0) {
        return new Object[0];
      }
      count *= listLength;
    }
    
    int[] mods = new int[paramLists.length + 1];
    mods[paramLists.length] = 1;
    for (int i = paramLists.length - 1; i >= 0; i--) {
      mods[i] = mods[i + 1] * paramLists[i].length; 
    }
    
    Object[] result = new Object[count];
    for (int i = 0; i < count; i++) {
      Object[] record = new Object[paramLists.length];
      Object[] indices = new Object[paramLists.length];
      for (int j = 0; j < paramLists.length; j++) {
        int index = (i / mods[j + 1]) % paramLists[j].length;
        indices[j] = index;
        record[j] = paramLists[j][index];
      }
      result[i] = record; 
    }
    return result;
  }

And here is how I would use it (a little cumbersome, but it does the job):

  private static Object[] versions() {
    ...
  }
  
  private static Object[] flushTypes() {
    ...
  }
  
  private static Object[] versions_FlushTypes() {
    return product(versions(), flushTypes());
  }

  @Test
  @Parameters(method = "versions_flushTypes")
  public void rangeValidity(Version version, FlushType) throws Exception {
    ...
  }

**Comment by theborakompanioni** [comment]
I'd also appreciate this feature. Is there any chance this will be implemented?

**Comment by jrmichael** [comment]
@theborakompanioni not in the nearest future. Sorry.
If I might suggest a workaround: create a method providing cartesian product of multiple data sets. Use [cartesianProduct from guava](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Sets.html#cartesianProduct(java.util.Set...)) (or anything else you like) and wrap it in some arrays

**Comment by piekarskim** [comment]
I'll try to give that a look.
