### ISSUE TITLE
method annotations get lost inside Description objects

### ISSUE THREAD

**Issue by McFoggy** [Pragmatists/JUnitParams#103]
inside [TestMethod#describe()](https://github.com/Pragmatists/JUnitParams/blob/JUnitParams-1.0.6/src/main/java/junitparams/internal/TestMethod.java#L109) the Description objects for each parametrized executions are built without inherent method annotations and without the class object.

This behavior leads in unavailable information for example for registered `org.junit.runner.notification.RunListener`

**Comment by woprzech** [comment]
We know it is an issue, and we cannot implement it. See #92

**Comment by McFoggy** [comment]
In my case I'll still use my PR ; it works as I expect and I can support the small overhead of reflection.
Thanks for your reply.
