### ISSUE TITLE
Support CSV quote character configuration in FileParameters

### ISSUE THREAD

**Issue by sumitjainn** [Pragmatists/JUnitParams#104]

**Comment by woprzech** [comment]
Hello, We think it would  be an interesting functionality. However it does not look like a core functionality for JUnitParams. It is a perfect candidate for a first official plugin. It can be easily implemented using `@CustomParameters` functionality and support of [commons-csv](https://commons.apache.org/proper/commons-csv/index.html) library. We are planning to implement it during some small hackathon. However you are welcome to implement it first.

**Comment by sumitjainn** [comment]
Sure, I will give it a try. Do you mean that it would not be part of this project? A separate artifact for the plugin?

**Comment by woprzech** [comment]
Yes, it should be separate jar, eg `JUnitPrams-csv` with new custom annotation, eg. `CsvParameters`. When you will finish, please inform us commenting that issue , we will fork your repo, deploy it to maven repository and inform community :wink:

**Comment by sumitjainn** [comment]
But, that would hardly be 3-4 classes, are you sure about this? Who would add a dependency just for this? Also you already have FileParameters in the core project, so CsvFileParameters wouldn't be so much out of place.

**Comment by woprzech** [comment]
We discussed it once again and we are sure that it doesn't fit to core library. As I said feel free to inform us if u want us to deploy your csv plugin to maven repository.
