### ISSUE TITLE
JUnitParamsRunner hides JUnit error message

### ISSUE THREAD

**Issue by jmflorezff** [Pragmatists/JUnitParams#113]
Consider the following test class:

```java
import junitparams.JUnitParamsRunner;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(JUnitParamsRunner.class)
public class MyTest {
    @BeforeClass
    public void shouldBeStatic() {
    }

    @Test
    public void test() {
    }
}
```

If you run it, you will simply get a `NullPointerException` instead of the JUnit message telling you that `shouldBeStatic` should effectively be static. If you remove or comment out the `@RunWith(JUnitParamsRunner.class)`, the error message shows up normally.

I don't know anything about JUnit internals but it would be nice if we got some kind of message instead of simply failing with an exception, if possible.

**Comment by adammichalik** [comment]
I see that [`JUnitParamsRunner#collectInitializationErrors`](https://github.com/Pragmatists/JUnitParams/blob/master/src/main/java/junitparams/JUnitParamsRunner.java#L404) overrides the superclass implementation ([`BlockJUnit4ClassRunner`](https://github.com/junit-team/junit4/blob/r4.12/src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java#L123), [`ParentRunner`](https://github.com/junit-team/junit4/blob/r4.12/src/main/java/org/junit/runners/ParentRunner.java#L124)) where a lot of checks are made with a much simplified own implementation. So in this case the sanity checks are omitted and JUnitParamsRunner proceeds with test execution of an invalid class. Pragmatists - any explanation for that?

**Comment by jrmichael** [comment]
We'll check it out. Thanks for raising.

**Comment by jrmichael** [comment]
We cannot use superclass implementation of `collectInitializationErrors` since it is restricting test methods to not have any parameters :)
I  picked up stuff that makes sense in superclassess and reimplemented it `JUnitParamsRunner`.

**Comment by stachenov** [comment]
This fix broke my [ParameterizedJUnitParams](stachenov/ParameterizedJUnitParams) because its very purpose is to allow parameterized constructors in classes with parameterized tests (to use both `Parameterized` and `JUnitParams`), and it now throws “Test class should have exactly one public zero-argument constructor”, which defeats the very idea. I'm sticking with 1.0.6 for now, and I'm quite happy with it, so it's not like it's anything critical.
