### ISSUE TITLE
 @Parameters formatting

### ISSUE THREAD

**Issue by whiter13** [Pragmatists/JUnitParams#115]
Feature request.

Do you plan to introduce some custom plugin for Intellij Idea (Android Studio should work as well) to format the `@Parameters` entries?

Like in below example:

```
@Test
@Parameters({
        "OPEN | OPEN",
        "CLOSE | CLOSE",
        "PRE_OPEN | PRE_OPEN",
})
```

So it will be formatted to:

```
@Test
@Parameters({
        "OPEN      | OPEN",
        "CLOSE     | CLOSE",
        "PRE_OPEN  | PRE_OPEN",
})
```

The second option is far more readable that the original one.

**Comment by woprzech** [comment]
Hello, unfortunately we are not planing to implement it. If you want you can add that plugin and we will add information about it to README :)
