### ISSUE TITLE
Encoding not used/ignored

### ISSUE THREAD

**Issue by pstueck** [Pragmatists/JUnitParams#119]
@FileParameters(value = "some.csv",encoding = "UTF-8")
@FileParameters(value = "some.csv")

Both do not use UTF-8 file encoding to load the file but rather ANSI!

Can be easily verified with an CSV containing a degree character (°), German diacritics like ä, ö, ü ...
They are just loaded as if they were ANSI characters (thus ° becomes &Acirc;°, and most German diacritics are no longer detectable at all).

**Comment by woprzech** [comment]
Can you reproduce that test case and create pull request with failing test? I pasted chars you introduced but it works for me.

**Comment by pstueck** [comment]
Yes - I can easily reproduce that no other encoding than ~~ANSI/ISO-8859-x~~ that of the test case itself seems to work ...

If the test case is ANSI encoded, ANSI encoded csv work.
If the test case is UTF-8 encoded, UTF-8 encoded csv work.

Here is what "file" (*nix/CygWin) says about the encoding of the attached files ...
>file *
ANSI.csv: ISO-8859 text
UTF8.csv: UTF-8 Unicode text
x-UTF-16LE-BOM.csv: Little-endian UTF-16 Unicode text, with no line terminators

[JUnitParametersEncoding.zip](https://github.com/Pragmatists/JUnitParams/files/1004012/JUnitParametersEncoding.zip)

**Comment by woprzech** [comment]
Hello, it took a while but finally we fixed that problem so thank you for highlighting it.

If you want to use this funcionality until we will release it you can change your file name in `@Parameters` annotation adding `classpath:` word

```java
    @Test
    @FileParameters(value = "classpath:with_special_chars.csv", encoding = "UTF-8")
    public void loadParamWithCorrectEncoding(String value) {
        //...
    }
```
