### ISSUE TITLE
Multiple `Class` parameters?

### ISSUE THREAD

**Issue by Poddster** [Pragmatists/JUnitParams#121]
I want to use multiple Class objects as parameters for a test, but I can't seem to perform the correct series of incantations to keep JUnitParams happy. My main issues are:

1. `@Parameters("blah.class")` doesn't work. I'd expect it to produce a `Class<blah>`, instead I get an `java.lang.IllegalArgumentException: argument type mismatch`.

2.  If I use `source =` or `method =` and return  `blah.class` then it works. But I can't return multiple `.class` types.

Some example code below. The test currently works, but try switching the `provideData` method to the commented-out one and it doesn't.

Am I doing something wrong or is it a problem in JUnitParams?

    import static org.hamcrest.MatcherAssert.assertThat;
    import static org.hamcrest.Matchers.containsString;
    import static org.hamcrest.Matchers.is;
    import static org.hamcrest.core.IsEqual.equalTo;
    
    import org.hamcrest.Matcher;
    import org.junit.Test;
    import org.junit.runner.RunWith;
    
    import junitparams.JUnitParamsRunner;
    import junitparams.Parameters;
    
    @SuppressWarnings("TestMethodWithIncorrectSignature")
    @RunWith(JUnitParamsRunner.class)
    public class BugTest {
    
        @Test
        @Parameters(method = "provideData")
        public void class_source(Class myClass) throws Exception {
            assertThat(myClass.toString(), containsString("My"));
        }
    
    //    @Test
    //    @Parameters({"MyFirstClass.class"})
    //    public void class_string(Class myClass) throws Exception {
    //        assertThat(myClass.getSimpleName(), is(equalTo("MyFirstClass")));
    //    }
    
    //    public static Object[] provideData() {
    //        return new Object[]{new Object[]{MyFirstClass.class, MySecondClass.class}};
    //    }
    
        public static Object[] provideData() {
            return new Object[]{new Object[]{MyFirstClass.class}};
        }
    
        class MyFirstClass {
    
        }
    
        class MySecondClass {
    
        }
    }

**Comment by adammichalik** [comment]
According to PR #42 you must provide a fully qualified class name for the automatic conversion to work. Check the test to the PR, it has an example.

**Comment by Poddster** [comment]
Well that solves problem 1, which is enough for me to be able to use this stuff in my tests. So thanks :)  (I'm surprised I didn't try fully qualified name in the first place, given that a third party class is trying to convert a string into a type name!)

But I can't see how to solve problem 2. i.e. in the code below `class_string` now works and passes, thanks to your info, but `class_source` fails with `java.lang.IllegalStateException: While trying to create object of class class java.lang.Class could not find constructor with arguments matching (type-wise) the ones given in parameters.` 



    package lol;
    import static org.hamcrest.MatcherAssert.assertThat;
    import static org.hamcrest.Matchers.containsString;
    import static org.hamcrest.Matchers.is;
    import static org.hamcrest.core.IsEqual.equalTo;

    import org.hamcrest.Matcher;
    import org.junit.Test;
    import org.junit.runner.RunWith;

    import junitparams.JUnitParamsRunner;
    import junitparams.Parameters;

    @SuppressWarnings("TestMethodWithIncorrectSignature")
    @RunWith(JUnitParamsRunner.class)
    public class BugTest {

        @Test
        @Parameters(method = "provideData")
        public void class_source(Class<?> myClass) throws Exception {
            System.out.println(MyFirstClass.class);
            assertThat(myClass.toString(), containsString("My"));
        }

        @Test
        @Parameters({
                "lol.BugTest$MyFirstClass",
                "lol.BugTest$MySecondClass"
        })
        public void class_string(Class<?> myClass) throws Exception {
            assertThat(myClass.getSimpleName(), is(equalTo("MyFirstClass")));
        }

        public static Object[] provideData() {
            return new Object[]{new Object[]{MyFirstClass.class, MySecondClass.class}};
        }

        class MyFirstClass {

        }

        class MySecondClass {

        }
    }

**Comment by adammichalik** [comment]
Your provider method should be 

```
public static Object[] provideData() {
        return new Object[]{new Object[]{MyFirstClass.class}, new Object[]{MySecondClass.class}};
    }
```

Every inner array is one test run and every array element is a method parameter. You want two runs with one parameter each

**Comment by Poddster** [comment]
PEBKAC in both cases.

Thanks for the help 👍
