### ISSUE TITLE
Execute @BeforeClass before resolving @Parameters

### ISSUE THREAD

**Issue by jfs** [Pragmatists/JUnitParams#124]
The test below will throw an exception because `getAwesomeParameters` is called before `setupEnvironment` and `RequiresJniLibrary` requires that the libraries are loaded to be instantiated.

I would like to see `JUnitParamsRunner` updated so that any methods annotated with `@BeforeClass` are called before `@Parameters` annotations are resolved.

```java
@RunWith(JUnitParamsRunner.class)
public final class ReallyCoolClassTests {

    @BeforeClass
    public final void setupEnvironment() {
      LibraryLoader.loadJniLibraries();
    }

    @Test
    @Parameters(method = "getAwesomeParameters()")
    public final void doSomethingAwesome_withDependency_returnsExpected(
        final RequiresJniLibrary dependency, final boolean expected) {
        final ReallyCoolClass subjectUnderTest = new ReallyCoolClass(dependency);

        final boolean result = subjectUnderTest.doSomethingAwesome();

        Assertions.assertThat(result).isEqualTo(expected);
    }

    private final Object getAwesomeParameters() {
      return new Object[][]{
          {new RequiresJniLibrary(1), true},
          {new RequiresJniLibrary(2), false}
      };
    }
}
```

**Comment by adammichalik** [comment]
See #37 for why that's not possible at the moment.
However, changing your `setupEnvironment()` to a plain static initializer should solve your issue since a static initializer is executed at class loading time, which must happen before any class method is executed, so before `getAwesomeParameters()`.

**Comment by jfs** [comment]
I'm not looking for why this isn't possible at the moment. I'm requesting this is supported in the future.
