### ISSUE TITLE
Cartesian product parameters.

### ISSUE THREAD

**Issue by Otanikotani** [Pragmatists/JUnitParams#135]
Hello,

I would like to request a new argument for parameters to be able to write something like:

```java

    @Test
    @Parameters(cartesian = {"1|2", "a|b"} )
    public void test_(int i, String str) throws Exception {
        System.out.println(i + " " + str);
    }
>>
1 a
1 b
2 a
2 b
```

So parameters are being provided as a cartesian product of given sets. 

This is useful when a unit under test is dependable on two parameters, f.e code like:

```java
public int foo(int i, int j) {
 if (i > 0 && (j == 1 || j == 2) {
  return 42;
 }
 return -1;
}
```

For this code I would like to have a test:

```java
    @Test
    @Parameters(cartesian = {"1|15|543745", "1|2"} )
    public void fooReturnAnswerToEverythingWheneverArgumentsAreProper(int i, int j) {
     assertThat(foo(i, j)).isEqualTo(42);
    }
```

So, I wanted to create a PR introducing this feature, but I am stuck at:

```java
public class ParametersFromCartesian implements ParametrizationStrategy {

    private final ParamsFromMethodCommon paramsFromMethodCommon;
    private final Parameters annotation;

    ParametersFromCartesian(FrameworkMethod frameworkMethod) {
        this.paramsFromMethodCommon = new ParamsFromMethodCommon(frameworkMethod);
        annotation = frameworkMethod.getAnnotation(Parameters.class);
    }

    @Override
    public Object[] getParameters() {
        String[] parameterSets = annotation.cartesian();
        int numberOfSets = parameterSets.length;
        String[][] all = new String[numberOfSets][];
        int totalNumberOfProducts = 1;
        for (int i = 0 ; i < parameterSets.length ; i++) {
            String[] parameterSet = Utils.splitAtCommaOrPipe(parameterSets[i]);
            all[i] = parameterSet;
            totalNumberOfProducts *= parameterSet.length;
        }
        List<StringBuilder> out = new ArrayList<StringBuilder>();
        cartesian(all, 0, out);
        return new Object[0];
    }

    ///... cartesian impl

    @Override
    public boolean isApplicable() {
        return annotation != null && annotation.cartesian().length > 0;
    }
```

The ugly thing is this `String[] parameterSet = Utils.splitAtCommaOrPipe(parameterSets[i]);` - is there a way to avoid splitting args by some delimiter? I need to split the given argument because I need to make a cartesian product of all of them, hence splitting is mandatory. Yet, I think it is a bad design since the strategy classes (other implementations) do not seem to be aware of how exactly params are to be splitted and splitting is actually happening later in the code. 

What would be your recommendations?

Thank you in advance!

**Comment by zbychupragmatists** [comment]
We have such feature but it's not documented anywhere ;-/

```
    @Test
    @CombinedParameters({"1,2", "a,b"})
    public void test_(int i, String str) throws Exception {
        System.out.println(i + " " + str);
    }
```

gives output

```
1 a
1 b
2 a
2 b
```

**Comment by Otanikotani** [comment]
Oh, wow, thank you @zbychupragmatists . I did not notice it. 

I see that `CombinedParametersProvider` uses `Utils.splitAtCommaOrPipe(parameterArray)` to get the list of params (my initial issue with my not needed not implementation). Is it as planned or considered to be a design flaw? 

I just want to understand the architecture better since I really like this library and use it a lot

**Comment by zbychupragmatists** [comment]
Splitting by comma or pipe is the desired behavior.
