### ISSUE TITLE
Support for Hierarchical Context runner 

### ISSUE THREAD

**Issue by npathai** [Pragmatists/JUnitParams#16]
JUnit 4.12 supports [Hierarchical context runner](https://github.com/junit-team/junit/blob/master/doc/ReleaseNotes4.12.md) so it would be great if we can provide that support in `JUnitParamsRunner`

``` java

@Runwith(JunitParamsHeirarchicalRunner.class)
public class ParentContext {

   // some tests go here

   @Runwith(JunitParamsHeirarchicalRunner.class)
   public class ChildContext {
        //some other tests go here
        ...
   }
}
```

**Comment by mchmielarz** [comment]
This is a really nice feature. @NarendraPathai: when do you expect to release it?

**Comment by NarendraPathai** [comment]
@mchmielarz Thanks I too think its really helpful in making tests more readable. I am using hierarchical context runner and I love it. I have worked on it a bit but its still work in progress. I hope to complete it this month.

**Comment by thekalinga** [comment]
@NarendraPathai 
Hi, Any luck with the implementation?

**Comment by NarendraPathai** [comment]
@thekalinga Recently I have been a bit busy with some work. I will get back to implementation this weekend. Plus I would have to get in touch with @bechte for his implementation in vanilla junit. We can  somehow use that implementation in JunitParams and so that we don't have to repeat the whole exercise again. Then all we have to do is extend it to provide support for junitparams as well. Link to his repo https://github.com/bechte/junit-hierarchicalcontextrunner

**Comment by bechte** [comment]
Hi, thanks for linking so I could see this discussion. I would be pleased to help. Maybe I can give you some background information on how I wrote the hierarchical context runner. That should help you to adapt the Param Runner to use it...

You should start looking at the method HierarchicalContextRunner.initialize(). You might want to extend your Runner from the HierarchicalContextRunner. It basically is a refactored version of the default JUnit Runner and it uses mostly all parts that the default runner uses as well. You could easily create your own MethodExecutor, that will be used to run the Statements and, therefore, link the extra logic required for the param handling in that MethodExecutor.

Unfortunately, JUnit itself does not have some kind of application context, where one could register itself for some special cases. This would make things much easier. But maybe JUnit will develop into this direction.

Please let me know if I can be of help.

**Comment by NarendraPathai** [comment]
@bechte Hey thanks for pitching in. I am new to junit contribution and am yet soaking in all the moving parts and internals of junit. I would appreciate your help. And BTW your runner is great I use it quite often .
