### ISSUE TITLE
Escaped comma with "\\" shows as "\" in Idea RUN

### ISSUE THREAD

**Issue by kyxap** [Pragmatists/JUnitParams#161]
```java
    @Test
    @Parameters({"text\\, my comma"})
    public void testParams(final String str) {
        System.out.println(str);
    }
``` 

![image](https://user-images.githubusercontent.com/3080529/54410149-7c46ac80-46a7-11e9-8d7b-2e394d63318d.png)

IDEA CE 2018.3.5 
JUnitParams 1.1.1

**Comment by peterjurkovic** [comment]
`\\` is reserved in Java for Backslash. What you see in your IDE is actually expected.
