### ISSUE TITLE
Added more shortcuts for primitive data type arrays [Issue 54 @ googlecode]

### ISSUE THREAD

**Issue by plipinski** [Pragmatists/JUnitParams#3]
Reported by mkucko, Dec 12, 2013
Writing my tests I noticed a lot of <code>new int[] {...}</code> statements.
I think more shortcuts could be useful.

----------------

#6 mkucko
Checkout https://github.com/mucaho/JArrayLiterals .

**Comment by apierzch** [comment]
We have decided to drop support for such helper-functions. Current dollar function is now deprecated and will be removed with release 2.0
