### ISSUE TITLE
Unable to pass newlines as a parameter

### ISSUE THREAD

**Issue by jalaziz** [Pragmatists/JUnitParams#30]
I was trying to use JUnitParams to help me parameterize a test for various types of line breaks. The tests were failing and upon further inspection, I came to realize that of the standard line breaks the parameter was an empty string.

Digging through the JUnitParams source, I believe the problem lies in Utils.splitAtCommaOrPipe(). However, I'm not entirely sure what the correct behavior should be. Whitespace should be trimmed in most cases, but it's feasible that you'd want whitespace to be passed as a parameter.

It seems that the workaround is simply to use a method or provider class to supply the values, so this may be intended behavior.

**Comment by michal-lipski** [comment]
I think that making whitespace characters available in parameters annotation can make code for parsing it too complicated. Besides, it will be more readable and explicit to provide them with method like you proposed.

Thanks for rising this.

**Comment by coopstah13** [comment]
I'm using a source class and it still does not work for me
