### ISSUE TITLE
How can I change the order of execution

### ISSUE THREAD

**Issue by fwang7** [Pragmatists/JUnitParams#37]
For now the order is looking like this be default:
parameterProvider() -> BeforeClass -> Test(parameters)
Can I switch the parameterProvider() and BeforeClass to make it like this?
BeforeClass -> parameterProvider() -> Test(parameters)

Thanks,
-feng

**Comment by jangalinski** [comment]
I would need this, too ... maybe the title for this should be: Allow Rule execution before provider execution.

**Comment by fzakaria** [comment]
I need this as well.
I would have assumed that the provider executes right before calling the method or something 
(naively) - and that BeforeClass executes before all else ?

**Comment by gaerfield** [comment]
I also stumbled on this. This sounds like a violation to JUnits-default-behaviour, because Methods annotated with `@BeforeClass` are needed to be static. `@Parameters(method = "... ")`-Methods does not to be. From my naive perspective, `@BeforceClass` should in every case be executed before parameterProvider-Methods. Does I miss something?

**Comment by jrmichael** [comment]
It cannot be implemented without a huge rewrite of entire library.
JUnit needs a complete description of the test run (classes and methods) before actually running them. Therefore we have to execute parameter providers first. 

`@BeforeClass` cannot be linked with parameter providers because they serve a different purpose. 

If you need to execute some code before calculating parameters consider using `@CustomParameters` functionality. It was introduces in JUnitParams 1.0.5

**Comment by gaerfield** [comment]
I'm sorry , but `@CustomerParameters` is not sufficient. Consider the following example:

``` java
@RunWith(JUnitParamsRunner.class)
public class SomeClassTest{
  private TestDataBuilder builder;
  private SomeClass sut; // system under test
  
  @Before
  public void init(){
     sut = expensiveInitializationOfSut();
     builder = expensiveBuildForTestData(sut);
  }

  @Test
  @Parameters(method = "provideTestData")
  public void testDoBusiness(String p1, String p2)
  {
     assertEquals(sut.processFast(p1),p2);
  }

  @Test
  @Parameters(method = "provideTestData")
  public void testDoBusiness(String p1, String p2)
  {
     assertEquals(sut.processSlow(p1),p2);
  }

  public Object[] provideTestData()
  {
      return new Object[][]{
           {builder.create("1"), "1"},
           {builder.create("2"), "2"}
      }
  }
  
}
```

I know, this test isn't nice. It has this nasty dependency between the SUT and the builder, where the builder is generic and magically creates some test-data which fits our SUT. Besides such smelly stuff, this test still is pretty obvious and easy to understand, just by using the `@Before`-Annotation. Usually the annotated Method gets more complex with building mocks, injections and other stuff. For the moment, lets say `expensiveInitializationOfSut` is doing that. Reusing the same test-Data for the different tests (see `provideTestData()`) maybe isn't common, but in my experience (with ugly legacy code) practical in some cases.

I tried to get a similar easy to read approach by your suggestion.
``` java
@RunWith(JUnitParamsRunner.class)
public class SomeClassTest{
  private SomeClass sut; // system under test
  
  @Retention(RetentionPolicy.RUNTIME)
  @Target(ElementType.METHOD)
  @CustomParameters(provider = MyConverter.class)
  public @interface SpecialParameters {
      String[] value() default {};
  }

  @Test
  @SpecialParameters({"1,1","2,2"})
  public void testDoBusiness(String p1, String p2)
  {
	 expensiveInitializationOfSut();
     assertEquals(sut.processFast(p1),p2);
  }

  @Test
  @Parameters
  @SpecialParameters({"1,1","2,2"})
  public void testDoBusiness(String p1, String p2)
  {
     expensiveInitializationOfSut();
     assertEquals(sut.processSlow(p1),p2);
  }

  private static class MyConverter
        implements ParametersProvider<SpecialParameters>
  {
     private TestDataBuilder builder;

	 public MyConverter()
     {
        builder = expensiveBuildForTestData();
     }

     @Override
     public void initialize(ProductUsageLineParameters parametersAnnotation)
     {
       value = parametersAnnotation.value(sut);
       // Ooops - Nullpointer, because sut not yet initialized
     }
   
     @Override
     public Object[] getParameters()
     {
        Object[] values = new Object[value.length];
        for (int i = 0; i < value.length; i++)
        {
          final String[] parameters = value[i].split(",");
          values[i] = new Object[]{builder.create(parameters[0]), parameters[1]};
        }
     }
  }
}
```

Lets put aside the smelly stuff in the TestCase itself and compare the two approaches:

* the dependency between the SUT und the TestDataBuilder makes it impossible to use the `@CustomParameters`-approach here in a clean way
* the introduction of a new Interface for defining a Builder for Test-Parameters is nice (i really like the idea). But it causes the introduction of another class and parsing the parameters which easily introduces new failures (i.e. if the parameters not given as expected)
* The flow of the test is not clear (compared to `@Before`). I had some difficulties in distinguishing what happens at `initialize()` and what at `getParameters()`. I guess this could happen also too readers, who are not familiar to JUnitParams, which in turn makes the test harder to maintain.
* The test is specialized to the requirements of JUnitParams, therefore migrating to alternative libraries in the future gets harder

If `@Before` or `@BeforeClass` is hard to support, maybe you can introduce an `@BeforeDataProviding`-Annotation (or similar)? This might not be an ideal solution, but seems to me more easy and straightforward then `@CustomParameters`. Did I miss another option?
