### ISSUE TITLE
Question: Support in Jenkins?

### ISSUE THREAD

**Issue by martinda** [Pragmatists/JUnitParams#38]
Is Jenkins able to interpret the JUnit XML file of JUnitParams today? Looks like a layer of reporting below the test name would be needed.

In this kind of report, what should show up as the test name in Jenkins? The name inside parens?

    <testsuite name="junitparams.usage.Samples_of_Usage_Test" time="0.005" tests="39" errors="0" skipped="0" failures="0">
    <testcase name="[0] SOME_VALUE (enums_as_params_in_annotation)" classname="junitparams.usage.Samples_of_Usage_Test" time="0.001"/>
    <testcase name="[1] OTHER_VALUE (enums_as_params_in_annotation)" classname="junitparams.usage.Samples_of_Usage_Test" time="0"/>
    </testsuite>

I can see users like myself wanting Jenkins to track the trend both at the test level and at the parameter level. Is that where JUnitParams is going overall?

**Comment by michal-lipski** [comment]
Jenkins displays names in test result, same as in IDE. So we will have display like this:
```
[0] SOME_VALUE (enums_as_params_in_annotation)
[1] OTHER_VALUE (enums_as_params_in_annotation)
```
Better reporting may be addressed by Jenkins plugin that will fold report based on method name or class.
But this is not in scope of JUnitParams.
