### ISSUE TITLE
String array gets not wrapped correct. [Issue 57 @ googlecode]

### ISSUE THREAD

**Issue by plipinski** [Pragmatists/JUnitParams#4]
Reported by juxeiier, Feb 5, 2014
Please see this question with a working example:
http://stackoverflow.com/questions/21582378/junitparams-not-working-with-string-array

Please review the safelyCastParamsToArray method.

**Comment by apierzch** [comment]
We decided to give up on `$` function - it does not relate to the JUnitParams functionality itself, it is just a helper than can be provided by other library if needed.
It was causing problems with tests accepting var-args.
