### ISSUE TITLE
Add self-description of parameters

### ISSUE THREAD

**Issue by renemischak** [Pragmatists/JUnitParams#43]
Hi,

the paramtrization implementation of JUnit offers the nice feature to self-describe the parameters like this:
`@Parameters(name = "{index}: add({0}+{1})={2}")`

I would really like to see this feature in JUnitParams. The test results in case of an error are much more understandable this way as you can see here: http://www.mkyong.com/wp-content/uploads/2009/05/junit-parameter-example-1.png

Any chance an active contributor might add it?

Regards
-René

**Comment by michal-lipski** [comment]
We already have this thanks to @Menliat 

See: https://github.com/Pragmatists/JUnitParams/pull/17

And examples are here: https://github.com/Pragmatists/JUnitParams/blob/master/src/test/java/junitparams/naming/NamingStrategyIsUsedByRunnerTest.java
