### ISSUE TITLE
Support for custom JUnit rule instead of RunWith

### ISSUE THREAD

**Issue by thekalinga** [Pragmatists/JUnitParams#49]
I am planning to use

1. [Spring MVC](https://github.com/spring-projects/spring-framework/commit/d1b1c4f888b5ab5c60cf4beb87f577143bdbebe7) - For Integration testing
2. [NestedRunner](https://github.com/NitorCreations/CoreComponents/tree/master/junit-runners) - For nesting test cases
3. [JUnitParams](https://github.com/Pragmatists/JUnitParams) - For [DDT](http://www.wikiwand.com/en/Data-driven_testing)
4. [Assumes](https://github.com/junit-team/junit.contrib/tree/master/assumes) - for specifying test dependencies
5. [Mockito](http://mockito.org/) - For mocking
6. [PowerMockito](https://code.google.com/p/powermock/) - For any mocking abuse I may need to do (I mean class/static method mocking)
7. [DBUnit](http://dbunit.sourceforge.net/) - For fiddling with DB data

Spring MVC in the current milestone version (4.2.0.RC1 or > 4.2 whenever the release happens) uses rules instead of runner to support integration with other runners. PowerMock currently supports Rules. Mockito supports Rule in the current Beta version (2.0.17-beta)

However, AFAIK, all others does not support rules. It would be better if this library can implement the runner using Junit Rule instead of Runner so that it can be compatible with all other runners to make a full blown testing stack. Else, people need to hack around to get most out of Java test frameworks.

Reference:

1. [Creating a custom runner for mockito](https://uthark.github.io/blog/2014/03/28/initializing-at-mocks-with-junit-at-rule/)
2. [Nested Runners Example](http://www.petrikainulainen.net/programming/testing/writing-clean-tests-small-is-beautiful/)

**Comment by thekalinga** [comment]
My mind map on how to integrate all of these is listed [here](https://gist.github.com/thekalinga/c55b652cc9cd6831608e)

**Comment by grzesuav** [comment]
Hi, I don't know if it will be helpfull, but I saw something similar : 
http://blog.schauderhaft.de/2012/12/16/writing-parameterized-tests-with-junit-rules/
and the code is : 
https://github.com/schauder/parameterizedTestsWithRules

**Comment by bennetelli** [comment]
I just tried to implement JUnitParams Rules instead of Runners . It's not possible to use method parameters of JUnit test methods. Therefore it's also impossible to use the existing JUnitParams implementation with Rules.

**Comment by jrmichael** [comment]
We also gave it a try some time ago. It is not possible. I am closing this issue.
