### ISSUE TITLE
(just a question) Plan to merge with JUnit?

### ISSUE THREAD

**Issue by hangtwenty** [Pragmatists/JUnitParams#51]
JUnit has Parameterize now: https://github.com/junit-team/junit/wiki/Parameterized-tests

but I like this JUnitParams code better, using an annotation. (You can look at the data and the implementation in 1 screenful. I already liked the similar feature in py.test, the Python test framework [which uses decorators](https://pytest.org/latest/parametrize.html) to parameterize.)

Is there a plan to get JUnitParams into JUnit, or will this remain as a independent plugin?

**Comment by npathai** [comment]
I don't think there is any plan for merging currently. JUnit is going for major version change to 5.0. And there are no such plans in near future AFAIK. @kcooney @marcphilipp am I correct?

**Comment by kcooney** [comment]
We don't have any immediate plans on the JUnit side, but longer term I would love to have an extension API in JUnit that would allow you to customize how test methods are defined and run for a given method. One use case would be supporting things like JUnitParams without a special runner.

Anyone on the Pragmatists team willing to work with us on that?

**Comment by kcooney** [comment]
More generally, I would like JUnit to create extension points that are better (read: more flexible, combinable)  so extension developers can write better extensions and be wildly successful.

Often, other projects can iterate much faster than the JUnit team can, so adding JUnitParams into JUnit proper wouldn't necessarily be the best thing for users of JUnitParams.

**Comment by hangtwenty** [comment]
Good stuff — love the idea of helping devs be "wildly successful — is there an issue for creating these extension points?

**Comment by kcooney** [comment]
@hangtwenty we don't have an issue tracking this currently. Feel free to add one if this is something you would like to see. I just don't want to design it in a vacuum, so if someone on the Pragmatists wants to help us design an extension point, that would help.

Someone could probably look at this pull and come up with a possible API for a MethodInvoker:
https://github.com/junit-team/junit/pull/1138

**Comment by hangtwenty** [comment]
Ah, I see. OK, so it's pretty much blocked by https://github.com/junit-team/junit/issues/1161, "JUnit needs a better story for extensibility." Then JUnitParams could provide its functionality in some way besides a whole different Runner. 

https://github.com/junit-team/junit/pull/1138 would also take care of it but unfortunately I'm not skilled enough with Java yet to take care of it.

Thanks for all the context!
