### ISSUE TITLE
String values are trimmed

### ISSUE THREAD

**Issue by mdeinum** [Pragmatists/JUnitParams#55]
I have an `@Parameters("foo", "123", " ")` for a certain testcase. However the `" "` is trimmed to an empty string. This makes my testcase fail.

I don't thing the parameter values should be trimmed.

**Comment by ffbit** [comment]
I have the same issue.

**Comment by jrmichael** [comment]
Yes, we are trimming whitespace characters. Since it would be a breaking change we won't be doing this anytime soon. Use  @ffbit's suggestion. 
BTW @mdeinum `" "` looks like a really special case. Maybe it deserves a separate test method with explicit parameterisation.

**Comment by jolros** [comment]
Doesn't this also fail with `method`?

```java
import static com.google.common.truth.Truth.assertThat;

import junitparams.JUnitParamsRunner;
import junitparams.Parameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(JUnitParamsRunner.class)
public class ParamsTest {

  public static String[] validStrings() {
    return new String[] {
      "    ", " f  ", "four",
    };
  }

  @Test
  @Parameters(method = "validStrings")
  public void testString(String value) throws Exception {
    assertThat(value.length()).isGreaterThan(3);
  }
}
```

**Comment by andreild** [comment]
Hello,

I'd also like to request that this bug be re-opened and fixed, please.

The fact that this would be a breaking change is less important than the fact that the framework misleads its users: if I write a unit test (using JUnitParams) checking for String equality I expect the test to succeed when the Strings passed in are equal, and to fail when they are not.

Right now, however, such a test would succeed when trim(String a).equals(trim(String b)). This affects not only methods that work on strings, but also methods that rely on previous methods having handled strings correctly.

Thank you for considering this.
