### ISSUE TITLE
Test with an object array parameter is invoked with incorrect parameter

### ISSUE THREAD

**Issue by adammichalik** [Pragmatists/JUnitParams#68]
JUnitParams 1.0.4

```java
@Test
@Parameters(method = "primitiveArray")
public void testPrimitiveArray(int[] ints) {
    assertThat(ints).containsExactly(0, 1);
}

@Test
@Parameters(method = "objectArray")
public void testObjectArray(Integer[] integers) {
    assertThat(integers).containsExactly(0, 1);
}

public Object[] primitiveArray() {
    return $($(new int[]{0, 1}));
}

public Object[] objectArray() {
    return $($(new Integer[]{0, 1}));
}
```

`testPrimitiveArray()` passes, `testObjectArray()` fails with

```
java.lang.AssertionError: 
Actual and expected should have same size but actual size was:
  <1>
while expected size was:
  <2>
Actual was:
  <[0]>
Expected was:
  <[0, 1]>
```

It seems a primitive array parameter is OK, but an object array is not.

See also http://stackoverflow.com/questions/21582378/junitparams-not-working-with-string-array

**Comment by adammichalik** [comment]
Ah, the cause is the infamous `$` method :) If you code it like this

```java
    public Object[] primitiveArray() {
        return new Object[]{new Object[]{new int[]{0, 1}}};
    }

    public Object[] objectArray() {
        return new Object[]{new Object[]{new Integer[]{0, 1}}};
    }
```

then it works. Up to you guys if you still want to tackle it.

**Comment by jrmichael** [comment]
Hi @adammichalik 

We decided not to support `$` method as it was producing too much confusion and problems. Check [javadocs](https://github.com/Pragmatists/JUnitParams/blob/master/src/main/java/junitparams/JUnitParamsRunner.java#L487) for this method.
