### ISSUE TITLE
@TestCaseName not displaying the contents of an array passed as an argument

### ISSUE THREAD

**Issue by piekarskim** [Pragmatists/JUnitParams#70]
Contents of an array passed as one of test parameters are currently not being displayed in the test's description generated by `@TestCaseName` annotation.

Example:

    private static final File JAVA_DIRECTORY = get("src/main/java/").toFile();
	private static final String[] NOT_ACCEPTABLE_IN_JAVA_DIRECTORY = {"groovy", "css", "html"};

	public Object[] filesNotAcceptedInDirectories() {
		return $(
				$(JAVA_DIRECTORY, NOT_ACCEPTABLE_IN_JAVA_DIRECTORY)
		);
	}

	@Test
	@Parameters(method = "filesNotAcceptedInDirectories")
	@TestCaseName("Verify that no files with extensions {1} are present in directory {0}")
	public void verifyFilesArePlacedInAppropriateDirectories(File directory, String[] unacceptableFiles) {
		assertThat(listFiles(directory, unacceptableFiles, true)).isEmpty();
	}

should display as:

`Verify that no files with extensions [groovy, css, html] are present in directory src\main\java`

but what we currently get is:
`Verify that no files with extensions String[] are present in directory src\main\java`

**Comment by mkordas** [comment]
@piekarskim :+1:

**Comment by adammichalik** [comment]
Pragmatists - see [my analysis](http://stackoverflow.com/a/34507907/466738) of this issue some time ago.

**Comment by piekarskim** [comment]
I'm familiar with it as it was me who posted this question on SE :)

Anyhow - I'll create a PR with a solution in a few minutes.
