### ISSUE TITLE
Deprecated $ method

### ISSUE THREAD

**Issue by piekarskim** [Pragmatists/JUnitParams#77]
Hi all,

According to the release notes for 1.0.5 
> Utility method $ was deprecated. It was causing too much problems and we decided not to support it any more. If you wish to keep using it, implement it in your own codebase.

What exactly are the problems? As this method is quite commonly used in our codebase we are considering implementing our own version and it'd be good to know the possible pitfalls.

Best,
Maciej

**Comment by mgryszko** [comment]
See the issue #68

**Comment by piekarskim** [comment]
Thanks @mgryszko !
