### ISSUE TITLE
test class with @parameter method is always instantiated.

### ISSUE THREAD

**Issue by anyone-can-test** [Pragmatists/JUnitParams#88]
When I run only one test class, one of test classes with @parameter method is always instantiated.
If I remove parameter annotation, the only one test is executed.

How can I prevent test class with @parameter not to be instantiated?

**Comment by jrmichael** [comment]
Can you show an example code that causes this behavior?

**Comment by anyone-can-test** [comment]
```java
@RunWith(JUnitParamsRunner.class)
public class PushMessageTest extends PushBase {

	static {
		System.out.println("hello");
	}

	@Test
	@Parameters(method = "getMessage")
	public void PushSendTest	(
									String targetType, String targetTo, ....
									
								) {
		...
	}							
}
```

gradle clean test --tests *otherClass
The console output prints hello.
If I remove Parameters annotation in PushSendTest, it does not print hello.

**Comment by jrmichael** [comment]
It is a static initialization block. It gets executed whenever classLoader loads PushMessageTest class regardless of `@Parameters` annotation presence. 

If you are not running tests for this class I am quite confident that it is not being instantiated.

**Comment by anyone-can-test** [comment]
I agree with you.
But, according to presence of @Parameters, "hello" is either printed or not.
I just want to execute xxx test class. But, PushMessageTest class is also instantiated.

**Comment by giggluigg** [comment]
@anyone Loading a class is different than instantiating an object of the same class. All static members and blocks are always executed when the class is loaded, even if no instance is constructed yet. If you remove the static modifier you should see that the block is not executed (hence the constructor not called), the annotation being present or not, unless you run some test in that class

**Comment by anyone-can-test** [comment]
I tested, the result is that gradle may have a issue.
The test code is the same.
In mvn, static is not executed as expected.
But in gradle, static is executed.

```
gradle clean test --tests *AppTest
com.score.test.AppTest > testA PASSED

com.score.test.AppTest > testB PASSED

com.score.test.AppTest > testC PASSED

com.score.test.AppTest > testD PASSED

com.score.test.Test2 STANDARD_OUT
    this is static.

--------------------------------------------------------------------
|  Results: SUCCESS (4 tests, 4 successes, 0 failures, 0 skipped)  |
--------------------------------------------------------------------
```

```
mvn clean test -Dtest=AppTest
Running com.score.test.AppTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.049 sec

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
```

```
Test2.java

@RunWith(JUnitParamsRunner.class)
public class Test2
{

        static {
                System.out.println("this is static.");
        }


```

**Comment by anyone-can-test** [comment]
In addition to

A. @Parameters({"a", "b"})
B. @Parameters(method="getMessage")

In gradle, with A the static is not executed.
with B the static is executed.

**Comment by jrmichael** [comment]
I don't know how gradle test runner is working under the hood. I am assuming it loads your class even it you are not running tests from it. Maybe the wildcard selector `*AppTest` causes it. While in maven you are calling a specific class (no need to load anything unrelated).

Either way I would strongly advise not to use static initialization blocks. They are hard to test and difficult to trace errors caused by them. JUnit has lots of other techniques that will serve you well for test setup.
