### ISSUE TITLE
Failed to read artifact descriptor for pl.pragmatists:JunitPArams:jar:1.0.5

### ISSUE THREAD

**Issue by workexperiencelit** [Pragmatists/JUnitParams#90]
I've tried maven clean and maven install, checked my maven proxy settings, the eclipse network connections settings and the version number, but I keep getting an error when trying to add version 1.0.5 as a dependency.

Eclipse version is 4.5.0 with embedded maven

**Comment by jrmichael** [comment]
Artifact is available in maven central repository. Double check your local configuration.
[http://search.maven.org/#artifactdetails%7Cpl.pragmatists%7CJUnitParams%7C1.0.5%7Cjar](http://search.maven.org/#artifactdetails%7Cpl.pragmatists%7CJUnitParams%7C1.0.5%7Cjar)
[https://mvnrepository.com/artifact/pl.pragmatists/JUnitParams/1.0.5](https://mvnrepository.com/artifact/pl.pragmatists/JUnitParams/1.0.5)
