### ISSUE TITLE
add @Repeatable

### ISSUE THREAD

**Issue by oterrien** [Pragmatists/JUnitParams#93]
Instead of specifying an array of parameters, it would be interesting to specify as many annotations as parameters to be used. 

**Example**: 

``` java
@RunWith(JUnitParamsRunner.class)
public class PersonTest {

  @Test
  @Parameters("17, false")
  @Parameters("22, true") 
  public void personIsAdult(int age, boolean valid) throws Exception {
    assertThat(new Person(age).isAdult(), is(valid));
  }  
}
```

This feature already exists in C# and is very useful to describe tests.

As described [here](http://docs.oracle.com/javase/tutorial/java/annotations/repeating.html), a beginning of solution would be:

``` java
@Retention(RetentionPolicy.RUNTIME)
@Repeatable(ParametersContainer.class)
public @interface Parameters {
...
}

@Retention(RetentionPolicy.RUNTIME)
@interface ParametersContainer{
    Parameters[] value();
}
```

**Comment by kovalskyi** [comment]
`@Repeatable` was introduced in Java 8, while JUnitParams is compiled to Java 6.

**Comment by jrmichael** [comment]
Sorry, we have to be backwards compatible with Java 6.
